version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - API_HOST=0.0.0.0
      - PYTHONPATH=/app
    volumes:
      - .:/app
    command: python -m pytest tests/core/ -v

volumes:
  redis_data:
  rabbitmq_data:
